### ISSUE TITLE
3-channel pngs are not accepted

### ISSUE THREAD

**Issue by kirbysayshi** [revisitors/readimage#1]
As the error message says... file an issue!

Ran into this while using a mac screenshot, which apparently are by default saved with only 3 channels. Is it simply a matter of taking the parsed data, and expanding the pixel data to include a 255 every 4th slot?

**Comment by brycebaril** [comment]
This is starting to hit me as well, it looks like the best way is to clone this behavior: https://github.com/darkskyapp/pngparse/blob/master/index.js#L14-L51 

calling that function would also work, but would be slower than just doing the conversion.

**Comment by brycebaril** [comment]
Fixed and pushed as 1.1.0

**Comment by kirbysayshi** [comment]
Cool, I'll try to give this a look this weekend.
